name: Generate Snake Game

on:
  workflow_dispatch:
  schedule:
    - cron: '0 14 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Git identity
        run: |
          git config user.name 'Maksew'
          git config user.email 'maxime.perrier@etu.unilim.fr'
      - uses: Platane/snk@v3
        with:
          github_user_name: Maksew
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
      - name: Commit and push if there's changes
        run: |
          git fetch
          git reset --hard HEAD 
          git checkout output || git checkout -b output
          git pull origin output --rebase
          git add dist/*.svg
          git commit -m "UPDATE: Snake Game output" || exit 0
          git push origin output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

