name: Generate Snake Game

on:
  push:
    branches:
      - output
  workflow_dispatch:
  schedule:
    - cron: '0 14 * * *'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: output # Ceci assure que le checkout est sur la branche 'output'
      - name: Set up Git identity
        run: |
          git config user.name 'Maksew'
          git config user.email 'maxime.perrier@etu.unilim.fr'
      - uses: Platane/snk@v3
        with:
          github_user_name: Maksew
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
      - name: Commit and push if there's changes
        run: |
          git fetch
          git add dist/*.svg
          git commit -m "UPDATE: Snake game output" || exit 0
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
